Airlines/Controllers/BuyController.cs
using System.Web.Mvc;

namespace Airlines.Controllers
{
    using _03.Services.Services;

    public class BuyController : Controller
    {
        private readonly TicketService ticketService;

        private readonly FlightsService flightsService;

        private readonly HtmlFormer htmlFormer;

        private readonly SmtpService smtpService;

        public BuyController()
        {
            this.ticketService = new TicketService();
            this.flightsService = new FlightsService();
            this.htmlFormer = new HtmlFormer();
            this.smtpService = new SmtpService();
        }

        // GET: Buy
        public ActionResult Ticket(int id, string userName, string email, string card, string secret)
        {
            var ticket = this.ticketService.Create(id, email);
            var html = this.htmlFormer.Form(this.flightsService.Get(id), ticket);

            this.smtpService.Send(html, email);
            this.ViewBag.Html = html;

            return View();
        }
    }
}

Airlines/Controllers/DetailController.cs
namespace Airlines.Controllers
{
    using System.Web.Mvc;
    using _03.Services.Services;

    public class DetailController : Controller
    {
        private readonly FlightsService flightsService;

        public DetailController()
        {
            this.flightsService = new FlightsService();
        }

        // GET: Detail
        public ActionResult Flight(int id)
        {
            var model = this.flightsService.Get(id);
            this.ViewBag.model = model;

            return View();
        }

        // GET: Buy
        public ActionResult Buy(int id)
        {
            var model = this.flightsService.Get(id);
            this.ViewBag.model = model;

            return View();
        }
    }
}

Airlines/Views/Detail/Buy.cshtml
@model dynamic
@{
    ViewBag.Title = "Замовлення";
}

<div class="container" ng-init="id = @ViewBag.model.Id">
    <div class="jumbotron" style="margin-top: 0; padding-top: 15px;">
        <form name="myForm" action="@Url.Action("Ticket", "Buy")">
            <input type="text" name="id" ng-model="id" style="display: none;"/>
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8 buy-form">
                    <h2 align="center" style="font-size: 44px;">Замовлення авіаквитка</h2>
                    <h2 align="center">@ViewBag.model.Name</h2>
                    <h2 align="center">Вартість: @ViewBag.model.Coast грн.</h2>
                    <hr/>
                    <div>
                        <h2 class="firstcol">ФИО*:</h2>
                        @* ng-class="{'error': myForm.userName.$error.required}"  *@
                        <input class="secondcol" type="text" name="userName" ng-model="userName" required/>
                    </div>
                    <div>
                        <h2 class="firstcol">Емейл*:</h2>
                        @*  ng-class="{'error': myForm.email.$error.required}" *@
                        <input class="secondcol" type="email" name="email" ng-model="email" required/>
                    </div>
                    <div>
                        <h2 class="firstcol">Номер карти*:</h2>
                        @* ng-class="{'error': !myForm.card.$valid}"  *@
                        <input id="iban" class="secondcol" type="text" tooltip="16 цифер" name="card" pattern="[0-9]{4}\s[0-9]{4}\s[0-9]{4}\s[0-9]{4}" ng-model="card" required maxlength="19" placeholder="1234 1234 1234 1234"/>
                        <div title="16 цифер" style="cursor: pointer; margin: auto 0; margin-left: 9px;">
                            <h4>?</h4>
                        </div>
                    </div>
                    <div>
                        <h2 class="firstcol">Секретний пароль*:</h2>
                        @* ng-class="{'error': !myForm.secret.$valid}"  *@
                        <input class="secondcol" type="text" name="secret" ng-model="secret" pattern="[0-9]{3}" required maxlength="3" placeholder="123"/>
                        <div title="3 цифри" style="cursor: pointer; margin: auto 0; margin-left: 9px;">
                            <h4>?</h4>
                        </div>
                    </div>
                    <div>
                        <h2 class="firstcol"></h2>
                        @*  ng-disabled="!myForm.secret.$valid || !myForm.card.$valid || myForm.email.$error.required || myForm.userName.$error.required" *@
                        <input type="submit"
                               class="btn btn-warning my-btn"
                               style="font-size: 28px; width: 280px; height: 60px;" title="Оплатити">
                        </input>
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
        </form>
    </div>
</div>

Airlines/Views/Detail/Flight.cshtml
@using _00.Common
@{
    ViewBag.Title = "Деталі рейсу";
}

<div class="container">
    <div class="jumbotron">
        <div>
            <h1 align="center">Детальна інформація</h1>
        </div>
        <div class="row" style="margin-top: 42px;">
            <div class="details col-md-6">
                <div>
                    <span>Назва:</span>
                    <span>@ViewBag.model.Name</span>
                </div>
                <div>
                    <span>Відпралення:</span>
                    <span>@DateTimeExpression.ToDayMonthYear(ViewBag.model.LeavingTime)</span>
                </div>
                <div>
                    <span>Прибуття:</span>
                    <span>@DateTimeExpression.ToDayMonthYear(ViewBag.model.Arrives)</span>
                </div>
                <div>
                    <span>Виліт з:</span>
                    <span>@ViewBag.model.AirportFrom (@ViewBag.model.CountryFrom)</span>
                </div>
                <div>
                    <span>Прибуття до:</span>
                    <span>@ViewBag.model.AirportTo (@ViewBag.model.CountryTo)</span>
                </div>
                <div>
                    <span>Вартість:</span>
                    <span>@ViewBag.model.Coast грн.</span>
                </div>
            </div>

            <div class="col-md-1"></div>
            <div class="col-md-4">
                <img src="../../Content/ticket.png" style="width: 280px; opacity: 0.75;"/>
                <a href="@Url.Action("Buy", "Detail", new {id = ViewBag.model.Id})">
                    <button type="button" class="btn btn-warning my-btn" style="font-size: 28px; width: 280px; height: 60px; margin-top: 10px;">ЗАМОВИТИ <i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
                </a>
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>
</div>

    